site_name: YAP Documentation
repo_url: https://github.com/kawaaii-programming/YetAnotherPluginDocs
repo_name: YetAnotherPluginDocs

nav:
  - Home: index.md
  - Setup: 
    - Dependencies: setup#dependencies
    - Configration Breakdown: setup#configration-breakdown
    - Default Configuration: setup#default-configuration
  - Modules:
    - Advancements: modules#advancements
    - Connections: modules#connections
    - Cross-chat: modules#cross-chat
  - Contribution:
    - Plugin: contribution#plugin
    - Documentation: contribution#documentation

theme:
  name: 'material'
  custom_dir: 'theme'
  font:
    text: Ubuntu
  palette:
    primary: 'teal'
    accent: 'cyan'

markdown_extensions:
  - codehilite
  - meta
  - admonition

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css

extra_javascript:
  - javascripts/extra.js