site_name: YAP Documentation
nav:
  - Home: index.md
  - Setup: 
    - Dependencies: setup#dependencies
    - Configuration: setup#configuration
  - Modules:
    - Advancements: modules#advancements
    - Connections: modules#connections
    - Cross-chat: modules#cross-chat
  - Contribution:
    - Intro: contribution#intro
    - Explanation: contribution#explanation

theme:
  name: 'material'
  custom_dir: 'theme'
  font:
    text: Ubuntu
  palette:
    primary: 'pink'
    accent: 'light pink'

markdown_extensions:
  - codehilite
  - meta

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css

extra_javascript:
  - javascripts/extra.js